### ISSUE TITLE
$\sqrt[x]{n}$

### ISSUE THREAD

**Issue by nr0728** [immccn123/lg-solution-formatter#97]
`$\sqrt[x]{n}$` 被格式化为 `$\sqrt_{x}{n}$`，明显不对

- Before: $\sqrt[x]{n}$
- After: $\sqrt_{x}{n}$

**Comment by nr0728** [comment]
呃 github 都预览不出来 After

**Comment by immccn123** [comment]
看一下 #98 这么改可行吗
